Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -25,6 +25,10 @@ jobs:
       run: |
         sudo apt-get update
         sudo apt-get install -y libcairo2 libcairo2-dev pkg-config python3-dev gir1.2-girepository-2.0
+        pkg-config --modversion girepository-2.0 || {
+          echo "girepository-2.0 is not installed or not found";
+          exit 1;
+        }
     - name: Install Python dependencies
       run: |
         python -m pip install --upgrade pip
